name: generate-mdx-files

on:
  pull_request:
    branches:
      - main
    paths:
      - 'fern/pages/cookbooks/**/*.mdx'
      - 'scripts/build-cookbooks/**/*'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bootstrap poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-in-project: false

      - name: Install Project Dependencies with Poetry
        shell: bash
        run: |
          poetry install

            - name: Check for mypy in pyproject.toml
      id: check_mypy
        run: |
          if grep -q 'mypy' pyproject.toml; then
            echo "mypy is specified in pyproject.toml, running..."
            poetry run mypy .
            echo "::set-output name=mypy_run::true"
          else
            echo "mypy is not specified in pyproject.toml, exiting."
            echo "::set-output name=mypy_run::false"
          fi

      - name: Build MDX Files
        if: steps.check_mypy.outputs.mypy_run == 'true'
        shell: bash
        run: poetry run python .github/scripts/build_cookbooks.py


      - name: Check for Changes in build-mdx Folder
        id: check_changes
        shell: bash
        run: |
          git add fern/pages/cookbooks*  # Ensure this path is correct
          git diff --cached --exit-code || echo "::set-output name=changes_detected::true"
        continue-on-error: true

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        shell: bash
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update cookbooks"
          git push origin HEAD
