name: check-mdx-links

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    name: check-mdx-links
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check internal MDX links
        run: node .github/scripts/check-mdx-internal-links.cjs
