name: preview-docs

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   ref: "${{ github.event.pull_request.merge_commit_sha }}"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        shell: bash
        run: pnpm install        

      - name: Run fern check
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: pnpm run docs:check

      - name: Generate preview URL
        id: generate-docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          OUTPUT=$(pnpm run docs:preview 2>&1) || true
          echo "$OUTPUT"
          URL=$(echo "$OUTPUT" | grep -oP 'Published docs to \K.*(?= \()')
          echo "Preview URL: $URL"
          echo "🌿 Preview your docs: $URL" > preview_url.txt

      - name: Comment URL in PR
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          filePath: preview_url.txt
