name: private-repo-sync

on:
  push: {}
 
jobs:
  sync-devx-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: (Python) GitHub app authentication
        id: push-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        with:
          owner: "cohere-ai"
          app-id: ${{ secrets.CI_GH_APP_ID }}
          private-key: ${{ secrets.CI_GH_APP_PRIVATE_KEY }}
      - name: mirror
        run: |
          eval `ssh-agent -s`
          git remote add private https://x-access-token:${{ steps.push-token.outputs.token }}@github.com/cohere-ai/cohere-developer-experience-private.git
          git push private HEAD:main